#####################################################################
# This is Jekyll's configuration file for this project.
#
# For more information, see the documentation:
#
#     https://jekyllrb.com/docs/configuration/
#####################################################################

# Site settings
title: Instance Gallery
description: >-
    A quasidigital art space that supports artists working across the spectrum of photographic media and whose residency program are exhibited on an intranet of autonomously networked servers provisioned at various physical locations.
human_language: en-US # The primary human language you write in.
timezone: America/New_York

# Project-specific settings.
# Needs https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#keeping-your-site-up-to-date-with-the-github-pages-gem

# Build settings
markdown: kramdown
exclude:
 - vendor
 - README.md

# Blog settings.
paginate: 5    # How many posts per HTML page.
paginate_path: "/blog/page/:num/"

# RSS feed settings.
rss:
    items:            10       # How many posts to include in blog RSS/Atom feeds.
    update_period:    weekly   # Acceptable values are: `hourly`, `daily`, `weekly`, `monthly`, or `yearly`.
    update_frequency: 1        # How many times in the feed_update_period the feed is updated.
    ttl:              60       # Number of minutes indicating how long to cache the channel content.
    editor_email:     editor@instancegallery.com # Email of the person responsible for channel content.
    webmaster_email:  webmaster@instancegallery.com # Email of the person responsible for technical issues.
    image:            logo.400x400.jpg

defaults:
    - scope:
          path: ""
      values:
          layout: default
